openapi: 3.0.0
info:
  title: Location Header API
  version: 1.0.0
paths:
  /create-resource:
    post:
      summary: Create Resource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: exampleName
                value:
                  type: string
                  example: exampleValue
      responses:
        '201':
          description: Resource created
          headers:
            Location:
              description: URL of the created resource
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 123
                  message:
                    type: string
                    example: Resource created successfully
