openapi: 3.0.0
info:
  title: Simple GraphQL API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5001
paths:
  /graphql:
    post:
      summary: Execute GraphQL queries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                variables:
                  type: object
                operationName:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    GraphQLQuery:
      type: object
      properties:
        query:
          type: string
        variables:
          type: object
        operationName:
          type: string
